aws/serverless-java-container

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsLambdaServletContainerHandler.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyRequestDispatcher.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/FilterChainHolder.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletResponseTest.java
aws-serverless-java-container-jersey/src/main/java/com/amazonaws/serverless/proxy/jersey/JerseyServletResponseWriter.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/SpringBootAppTest.java

Fixed `ClassCastException` and early flushBuffer calls reported in #105

Fixing forward and include filter issues with Spring

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletResponse.java

Hi, 
HttpServletAPiResponse sendRedirect method should send a temporary redirect response to the client.
Best Regards.

Send a temporary redirect response in AwsHttpSerletResponse sendRedirect

---

archetypes/jersey/pom.xml
archetypes/jersey/src/main/resources/archetype-resources/pom.xml
archetypes/spark/pom.xml
archetypes/spark/src/main/resources/archetype-resources/pom.xml
archetypes/spring/pom.xml
archetypes/spring/src/main/resources/archetype-resources/pom.xml
archetypes/springboot/pom.xml
archetypes/springboot/src/main/resources/archetype-resources/pom.xml
aws-serverless-java-container-core/pom.xml
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/EncodingQueryStringParameterMap.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/testutils/AwsProxyRequestBuilder.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/ContainerConfig.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequestTest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestTest.java
aws-serverless-java-container-jersey/pom.xml
aws-serverless-java-container-jersey/src/main/java/com/amazonaws/serverless/proxy/jersey/JerseyHandlerFilter.java
aws-serverless-java-container-jersey/src/test/java/com/amazonaws/serverless/proxy/jersey/EchoJerseyResource.java
aws-serverless-java-container-jersey/src/test/java/com/amazonaws/serverless/proxy/jersey/JerseyAwsProxyTest.java
aws-serverless-java-container-jersey/src/test/java/com/amazonaws/serverless/proxy/jersey/JerseyParamEncodingTest.java
aws-serverless-java-container-spark/pom.xml
aws-serverless-java-container-spark/src/main/java/com/amazonaws/serverless/proxy/spark/SparkLambdaContainerHandler.java
aws-serverless-java-container-spark/src/test/java/com/amazonaws/serverless/proxy/spark/HelloWorldSparkTest.java
aws-serverless-java-container-spring/pom.xml
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/SpringBootAppTest.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/springbootapp/TestController.java
pom.xml

These commits address issues: #153, #158, #150, #156, #154, #151, and #146

Merging bug fixes for release 1.1.1

---

samples/springboot2/pet-store/sam.yaml

Related to https://github.com/awslabs/aws-sam-cli/issues/932

Handler typo - aws-sam-cli/issues/932

---

samples/micronaut/pet-store/README.md

It wasn't initially super obvious to me how to run this locally, but I was able to figure it out. I'm hoping to make it clearer to anyone else looking at it in the future via this change.

Further differentiates running via SAM vs AWS

---

aws-serverless-struts2-archetype/src/main/resources/archetype-resources/build.gradle
aws-serverless-struts2-archetype/src/main/resources/archetype-resources/pom.xml
pom.xml

#355 
Changed version of `slf4j-api` from *1.8.0-beta4* to *1.7.30*.

Fix for issue #355

---

aws-serverless-java-container-springboot2/pom.xml
aws-serverless-java-container-struts2/pom.xml

updated spring version

---

aws-serverless-jersey-archetype/src/main/resources/archetype-resources/pom.xml
aws-serverless-spark-archetype/src/main/resources/archetype-resources/build.gradle
aws-serverless-spark-archetype/src/main/resources/archetype-resources/pom.xml
aws-serverless-spring-archetype/src/main/resources/archetype-resources/build.gradle
aws-serverless-struts2-archetype/src/main/resources/archetype-resources/build.gradle
aws-serverless-struts2-archetype/src/main/resources/archetype-resources/pom.xml
pom.xml
samples/jersey/pet-store/build.gradle
samples/jersey/pet-store/pom.xml
samples/spark/pet-store/build.gradle
samples/spark/pet-store/pom.xml
samples/spring/pet-store/build.gradle
samples/struts2/pet-store/build.gradle
samples/struts2/pet-store/pom.xml

Upgrade Jackson version to 2.12.0 (CVE-2020-25649)

Upgrade Jackson version to 2.12.0 (CVE-2020-25649)

---

aws-serverless-java-container-core/pom.xml
aws-serverless-java-container-spring/pom.xml
aws-serverless-java-container-springboot2/pom.xml
aws-serverless-spring-archetype/src/main/resources/archetype-resources/build.gradle
aws-serverless-spring-archetype/src/main/resources/archetype-resources/pom.xml
samples/spring/pet-store/pom.xml

Update Spring minor versions

---

aws-serverless-jersey-archetype/src/main/resources/archetype-resources/build.gradle
aws-serverless-spark-archetype/src/main/resources/archetype-resources/build.gradle
aws-serverless-spring-archetype/src/main/resources/archetype-resources/build.gradle
aws-serverless-springboot-archetype/src/main/resources/archetype-resources/build.gradle
aws-serverless-springboot2-archetype/src/main/resources/archetype-resources/build.gradle
aws-serverless-struts2-archetype/src/main/resources/archetype-resources/build.gradle
samples/jersey/pet-store/build.gradle
samples/micronaut/pet-store/build.gradle
samples/spark/pet-store/build.gradle
samples/spring/pet-store/build.gradle
samples/springboot/pet-store/build.gradle
samples/springboot2/pet-store/build.gradle
samples/struts2/pet-store/build.gradle

Gradle compile/ testCompile no longer works with latest Gradle releases, replace with implementation

Gradle compile/ testCompile no longer works with latest Gradle releases

---

aws-serverless-java-container-struts2/pom.xml
aws-serverless-java-container-struts2/src/main/java/com/amazonaws/serverless/proxy/struts2/Struts2LambdaHandler.java
aws-serverless-spring-archetype/src/main/resources/archetype-resources/build.gradle
aws-serverless-spring-archetype/src/main/resources/archetype-resources/pom.xml
aws-serverless-struts2-archetype/src/main/resources/archetype-resources/build.gradle
aws-serverless-struts2-archetype/src/main/resources/archetype-resources/pom.xml
samples/spring/pet-store/build.gradle
samples/spring/pet-store/pom.xml
samples/struts2/pet-store/build.gradle
samples/struts2/pet-store/pom.xml

Merge #395 from dev to fix CI build

Upgrade to latest available Struts GA version 2.5.26

---

aws-serverless-java-container-spring/src/main/java/com/amazonaws/serverless/proxy/spring/SpringLambdaContainerHandler.java
aws-serverless-java-container-spring/src/main/java/com/amazonaws/serverless/proxy/spring/SpringProxyHandlerBuilder.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/extensibility/CustomServlet.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/extensibility/CustomServletTest.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/extensibility/CustomSpringLambdaContainerHandler.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/extensibility/CustomSpringProxyHandlerBuilder.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/extensibility/StreamLambdaHandler.java

Changed some things to improve extensibility/ inheritance. Tried to use it with an app that uses Spring but not Spring Web MVC. Still boilerplate code involved to achieve it, would welcome any feedback to simplify it.

Improve extensibility, allow other servlets besides DispatcherServlet

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/HttpApiV2AuthorizerMap.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/model/HttpApiV2ProxyRequestTest.java

#386 
Add Lambda authorizers in addition to existing JWT authorizers 
see also https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html

Add support for Lambda Authorizers in combination with 2.0 payload

---

aws-serverless-struts-archetype/src/main/resources/archetype-resources/build.gradle
aws-serverless-struts-archetype/src/main/resources/archetype-resources/pom.xml
samples/struts/pet-store/README.md
samples/struts/pet-store/build.gradle
samples/struts/pet-store/pom.xml
samples/struts/pet-store/src/main/resources/struts.xml
samples/struts/pet-store/template.yml
samples/struts/pet-store/test-event.json

https://github.com/awslabs/aws-serverless-java-container/issues/479
*Issue #479, if available:* Broken struts pet-store sample project
Fix the broken struts pet-store sample project
`sam local invoke -e test-event.json`
**Output**
```
Invoking com.amazonaws.serverless.proxy.struts.StrutsLambdaHandler::handleRequest (java11)
Skip pulling image and use local one: public.ecr.aws/sam/emulation-java11:rapid-1.53.0-x86_64.
Mounting /Users/geppertj/Documents/Private/Projects/aws-serverless-java-container/samples/struts/pet-store/.aws-sam/build/PetStoreFunction as /var/task:ro,delegated inside runtime container
START RequestId: 63d0a0fd-3766-4ab4-90b2-e15d4a2be939 Version: $LATEST
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See …
```

Fix broken struts pet-store sample project

---

README.md

Add link to Spring on Lambda YT playlist

---

samples/springboot3/pet-store/README.md

Update Springboot3 sample app's README

feat: Support Jakarta EE along with Spring Boot 3 support - update Springboot3 sample app's README

---

aws-serverless-jersey-archetype/src/main/resources/archetype-resources/build.gradle
aws-serverless-jersey-archetype/src/main/resources/archetype-resources/pom.xml
aws-serverless-jersey-archetype/src/main/resources/archetype-resources/src/test/java/StreamLambdaHandlerTest.java
aws-serverless-spark-archetype/src/main/resources/archetype-resources/build.gradle
aws-serverless-spark-archetype/src/main/resources/archetype-resources/pom.xml
aws-serverless-spark-archetype/src/main/resources/archetype-resources/src/test/java/StreamLambdaHandlerTest.java
aws-serverless-spring-archetype/src/main/resources/archetype-resources/build.gradle
aws-serverless-spring-archetype/src/main/resources/archetype-resources/pom.xml
aws-serverless-spring-archetype/src/main/resources/archetype-resources/src/test/java/StreamLambdaHandlerTest.java
aws-serverless-springboot3-archetype/src/main/resources/archetype-resources/build.gradle
aws-serverless-springboot3-archetype/src/main/resources/archetype-resources/pom.xml
aws-serverless-springboot3-archetype/src/main/resources/archetype-resources/src/test/java/StreamLambdaHandlerTest.java
aws-serverless-struts-archetype/src/main/resources/archetype-resources/build.gradle
aws-serverless-struts-archetype/src/main/resources/archetype-resources/pom.xml
aws-serverless-struts-archetype/src/main/resources/archetype-resources/src/test/java/StreamLambdaHandlerTest.java

[561](https://github.com/awslabs/aws-serverless-java-container/issues/561)
Junit version upgraded to latest version in jersey archetype

junit version changed

---

samples/springboot3/pet-store-native/Dockerfile
samples/springboot3/pet-store-native/README.md
samples/springboot3/pet-store-native/pom.xml
samples/springboot3/pet-store-native/template.yaml

Adapted GraalVM test to build during container run with x86
- [X ] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [X ] I confirm that I've made a best effort attempt to update all relevant documentation.

GraalVM sample

---

aws-serverless-java-container-springboot3/pom.xml

To ensure latest updates from s-c-function (e.g., https://github.com/spring-cloud/spring-cloud-function/commit/bee5e0b1635dff4f0331b1e90a37c1e8c477d87a) are picked up

Uograde SCF to 4.1.2-SNAPSHOT

---

aws-serverless-java-container-springboot3/src/main/java/com/amazonaws/serverless/proxy/spring/AwsSpringWebCustomRuntimeEventLoop.java
aws-serverless-java-container-springboot3/src/main/java/com/amazonaws/serverless/proxy/spring/AwsSpringWebRuntimeInitializer.java

- Removed logging of AWS credentials.

Remove logging of aws credentials
