aws-serverless-java-container-spring/pom.xml
aws-serverless-java-container-spring/src/main/java/com/amazonaws/serverless/proxy/spring/LambdaSpringApplicationInitializer.java
aws-serverless-java-container-spring/src/main/java/com/amazonaws/serverless/proxy/spring/SpringLambdacontainerHandler.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/SpringAwsProxyTest.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/echoapp/EchoSpringAppConfig.java

Added ability to provide custom ApplicationContext. For Spring testing, made objects that can potentially be shared by multiple tests classes and methods beans.

Provide ApplicationContext instead of Config classes

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestTest.java

I've tried to use the Spring EchoApp in the real AWS Lambda and the `/echo/query-string` GET-request was failed for non-set query parameters. It happened because in this case `AwsProxyRequest.queryStringParameters` remains uninitialized.

Fix NPE for null in the query parameters

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/model/AwsProxyRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/testutils/AwsProxyRequestBuilder.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/SpringAwsProxyTest.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/echoapp/EchoResource.java

Implementing `getRequestURL()` on the HttpServletRequest object addresses https://github.com/awslabs/aws-serverless-java-container/issues/10.  In the process, I also adjusted the following methods, which all contribute to `getRequestURL()`
* getServerName()
* getServer/LocalPort()
* getContextPath()
Tests added and AwsProxyRequestBuilder adjusted

Implement HttpServletRequest.getRequestURL()

---

README.md
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/LambdaContainerHandler.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsFilterChainManager.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsLambdaServletContainerHandler.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsServletContext.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/FilterChainHolder.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/FilterChainManager.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/FilterHolder.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/filters/UrlPathValidator.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/testutils/AwsProxyRequestBuilder.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsFilterChainManagerTest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequestTest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/FilterHolderTest.java
aws-serverless-java-container-spark/src/main/java/com/amazonaws/serverless/proxy/spark/SparkLambdaContainerHandler.java
aws-serverless-java-container-spark/src/main/java/com/amazonaws/serverless/proxy/spark/embeddedserver/LambdaEmbeddedServer.java
aws-serverless-java-container-spring/pom.xml
aws-serverless-java-container-spring/src/main/java/com/amazonaws/serverless/proxy/spring/LambdaSpringApplicationInitializer.java
aws-serverless-java-container-spring/src/main/java/com/amazonaws/serverless/proxy/spring/SpringLambdaContainerHandler.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/SpringAwsProxyTest.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/SpringServletContextTest.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/echoapp/ContextResource.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/echoapp/CustomHeaderFilter.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/echoapp/EchoResource.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/echoapp/EchoSpringAppConfig.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/echoapp/model/ValidatedUserModel.java
samples/jersey/pet-store/src/main/java/com/amazonaws/serverless/sample/jersey/LambdaHandler.java
samples/spring/pet-store/src/main/java/com/amazonaws/serverless/sample/spring/LambdaHandler.java

Merging support for servlet filters into master branch. This should address issue #15. For containers that support the servlet specs you can use a `StartupHandler` to register filters in the servlet context:
```java
handler.setStartupHandler(c -> {
FilterRegistration.Dynamic registration = c.addFilter("CustomHeaderFilter", CustomHeaderFilter.class);
// update the registration to map to a path
registration.addMappingForUrlPatterns(EnumSet.of(DispatcherType.REQUEST), true, "/*");
// servlet name mappings are disabled and will throw an exception
});
```
The container does NOT load filter implementations annotated with `@WebFilter` automatically, they still have to be registered in the `onStartup` method. This is to avoid impacting cold starts.

Servlet filters support

---

samples/spark/pet-store/README.md

change references from "jersey" to "spark"

Update samples/spark README.md

---

samples/jersey/pet-store/pom.xml
samples/spark/pet-store/pom.xml
samples/spring/pet-store/pom.xml

Fix version reference to this library (latest release, 0.4)
updated ref lets maven compile before `cloudformation package`'ing

update samples' pom.xml bump version to use LATEST

---

.travis.yml
README.md
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/jaxrs/AwsProxySecurityContext.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/model/ApiGatewayAuthorizerContext.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/model/AwsProxyRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/model/CognitoAuthorizerClaims.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/testutils/AwsProxyRequestBuilder.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/model/ApiGatewayAuthorizerContextTest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/model/CognitoAuthorizerClaimsTest.java

Merge support for Cognito User Pool authorizers (Issue #24)

Cognito user pool

---

README.md
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletResponse.java
aws-serverless-java-container-jersey/src/main/java/com/amazonaws/serverless/proxy/jersey/JerseyAwsProxyRequestReader.java
aws-serverless-java-container-jersey/src/main/java/com/amazonaws/serverless/proxy/jersey/factory/AwsProxyServletContextFactory.java
aws-serverless-java-container-jersey/src/main/java/com/amazonaws/serverless/proxy/jersey/factory/AwsProxyServletRequestFactory.java
aws-serverless-java-container-jersey/src/test/java/com/amazonaws/serverless/proxy/test/jersey/EchoJerseyResource.java
aws-serverless-java-container-jersey/src/test/java/com/amazonaws/serverless/proxy/test/jersey/JerseyAwsProxyTest.java

Servlet improvements

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/model/ApiGatewayRequestContext.java

Hi,
ApiGateway provides an additional field. I believe it is related to x-ray but I can't be sure. It would be nice to expose it though, so lambda code can take advantage of it.

Take into account the new `path` field.

---

README.md
aws-serverless-java-container-core/pom.xml
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/AwsProxyExceptionHandler.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/LambdaContainerHandler.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletResponse.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsLambdaServletContainerHandler.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsServletContext.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/filters/UrlPathValidator.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsFilterChainManagerTest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletResponseTest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/FilterHolderTest.java
aws-serverless-java-container-jersey/pom.xml
aws-serverless-java-container-jersey/src/main/java/com/amazonaws/serverless/proxy/jersey/JerseyLambdaContainerHandler.java
aws-serverless-java-container-jersey/src/main/java/com/amazonaws/serverless/proxy/jersey/factory/AwsProxyServletRequestFactory.java
aws-serverless-java-container-spark/pom.xml
aws-serverless-java-container-spark/src/main/java/com/amazonaws/serverless/proxy/spark/SparkLambdaContainerHandler.java
aws-serverless-java-container-spark/src/main/java/com/amazonaws/serverless/proxy/spark/embeddedserver/LambdaEmbeddedServer.java
aws-serverless-java-container-spring/pom.xml
aws-serverless-java-container-spring/src/main/java/com/amazonaws/serverless/proxy/spring/LambdaSpringApplicationInitializer.java
aws-serverless-java-container-spring/src/main/java/com/amazonaws/serverless/proxy/spring/SpringLambdaContainerHandler.java
pom.xml
samples/jersey/pet-store/pom.xml
samples/spark/pet-store/pom.xml
samples/spark/pet-store/src/main/java/com/amazonaws/serverless/sample/spark/JsonTransformer.java
samples/spark/pet-store/src/main/java/com/amazonaws/serverless/sample/spark/LambdaHandler.java
samples/spring/pet-store/pom.xml
samples/spring/pet-store/src/main/java/com/amazonaws/serverless/sample/spring/LambdaHandler.java
samples/spring/pet-store/src/main/java/com/amazonaws/serverless/sample/spring/StreamLambdaHandler.java

Addressed issues #21, #26, #44, #50, and #51. Preparing to release 0.6

Merge issues for release 0.6

---

aws-serverless-java-container-core/pom.xml
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/AwsProxyExceptionHandler.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/model/ContainerConfig.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletResponse.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/FilterChainHolder.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/FilterChainManager.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsFilterChainManagerTest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletResponseTest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestReaderTest.java
aws-serverless-java-container-jersey/src/main/java/com/amazonaws/serverless/proxy/jersey/JerseyAwsProxyRequestReader.java
aws-serverless-java-container-jersey/src/main/java/com/amazonaws/serverless/proxy/jersey/JerseyResponseWriter.java
aws-serverless-java-container-jersey/src/test/java/com/amazonaws/serverless/proxy/jersey/JerseyAwsProxyTest.java
aws-serverless-java-container-spark/pom.xml
aws-serverless-java-container-spark/src/test/java/com/amazonaws/serverless/proxy/spark/HelloWorldSparkTest.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/SpringAwsProxyTest.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/SpringServletContextTest.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/echoapp/ContextResource.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/echoapp/EchoResource.java
pom.xml

* Fixed `FilterChainHolder` to address issue #56 
* Added url encoding decoding with configurable charset to address #53 
* Changed Jersey URI initialization to use `URIBuilder` for issue #59 
* `addCookie` method fixes for #51

Merging servlet improvements fixes

---

README.md
aws-serverless-java-container-core/pom.xml
aws-serverless-java-container-jersey/pom.xml
aws-serverless-java-container-spark/pom.xml
aws-serverless-java-container-spark/src/main/java/com/amazonaws/serverless/proxy/spark/SparkLambdaContainerHandler.java
aws-serverless-java-container-spark/src/main/java/com/amazonaws/serverless/proxy/spark/embeddedserver/LambdaEmbeddedServer.java
aws-serverless-java-container-spark/src/main/java/com/amazonaws/serverless/proxy/spark/embeddedserver/LambdaEmbeddedServerFactory.java
aws-serverless-java-container-spark/src/test/java/com/amazonaws/serverless/proxy/spark/HelloWorldSparkTest.java
aws-serverless-java-container-spark/src/test/java/com/amazonaws/serverless/proxy/spark/InitExceptionHandlerTest.java
aws-serverless-java-container-spark/src/test/java/com/amazonaws/serverless/proxy/spark/SparkLambdaContainerHandlerTest.java
aws-serverless-java-container-spring/pom.xml
pom.xml
samples/spark/pet-store/pom.xml

Upgrade to Spark 2.6.0 to address issue #42. This new release is not compatible with older versions of Spark since there was a breaking change in the Spark `EmbeddedServer` interface

Spark upgrade

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/model/AwsProxyRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletResponse.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpSession.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsLambdaServletContainerHandler.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsServletContext.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/FilterChainHolder.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/FilterChainManager.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/FilterHolder.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/testutils/AwsProxyRequestBuilder.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsFilterChainManagerTest.java
aws-serverless-java-container-spark/src/main/java/com/amazonaws/serverless/proxy/spark/SparkLambdaContainerHandler.java
aws-serverless-java-container-spring/src/main/java/com/amazonaws/serverless/proxy/spring/SpringBootLambdaContainerHandler.java
aws-serverless-java-container-spring/src/main/java/com/amazonaws/serverless/proxy/spring/SpringLambdaContainerHandler.java

I apologize for so many changes.
This adds support for Spring Boot, Servlet API, and Spring MVC. 
* added new handler for Spring Boot (entire loader lifecycle)
* changed handling of servlet in the end of filter chain to better mimic Servlet API behavior, instead of after all Filters have finished executing
Proof of concept is https://github.com/ceefour/wicket8serverless , deployed at https://im9ntgimlc.execute-api.us-east-1.amazonaws.com/prod/
Hopefully this can pave way to official support from Spring Cloud Function, see https://github.com/spring-cloud/spring-cloud-function/issues/107

Proof-of-concept of Spring Boot, Servlet API, and Spring MVC support

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/FilterHolder.java

As I mentioned on #68, I ran into an NPE when trying to configure a filter. Since there is no way to initialize `FilterHolder.filterConfig`, and it contains the `FilterHolder.Config` class, I just initialized with an instance of that.

Initialize filterConfig to avoid NPE

---

aws-serverless-java-container-jersey/src/main/java/com/amazonaws/serverless/proxy/jersey/JerseyHandlerFilter.java
aws-serverless-java-container-jersey/src/test/java/com/amazonaws/serverless/proxy/jersey/JerseyAwsProxyTest.java

Addresses issue #112. This is a new bug introduced with the fixes for #84. Added unit tests.

Fix routing issue with Jersey when stripBasePath is configured

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequest.java
aws-serverless-java-container-spring/pom.xml
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/SpringBootAppTest.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/springbootapp/LambdaHandler.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/springbootapp/TestApplication.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/springbootapp/TestController.java

Added unit test to validate the proposed solution for #111 and warning log messages in request object when a framework tries to access the session

Spring security tests

---

archetypes/jersey/src/main/resources/archetype-resources/pom.xml
archetypes/spark/src/main/resources/archetype-resources/pom.xml
archetypes/spring/src/main/resources/archetype-resources/pom.xml
archetypes/springboot/src/main/resources/archetype-resources/pom.xml
aws-serverless-java-container-core/pom.xml
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequest.java
aws-serverless-java-container-spark/src/test/java/com/amazonaws/serverless/proxy/spark/HelloWorldSparkStreamTest.java
aws-serverless-java-container-spring/pom.xml

Preparing for 1.0.1 release to address critical vulnerability [CVE-2018-5968](https://nvd.nist.gov/vuln/detail/CVE-2018-5968) in Jackson dependency.

Bump in jackson dependency version

---

archetypes/spark/src/main/resources/archetype-resources/pom.xml
aws-serverless-java-container-spark/pom.xml
samples/spark/pet-store/pom.xml

The framework currently uses spark 2.7.1.  Spark was updated in March 2018 to version 2.7.2.  The release notes say:
Spark 2.7.2 fixes a security problem in the serving of static files. It also adds support for specific keystore aliases and bumps Jetty to the latest version
This commit solely updates the version of spark in all three spark pom.xml files.

Upgrade spark to 2.7.2. Spark 2.7.2 fixes a security problem

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequest.java

Do not call SecurityUtils.getValidFilePath when processing a Multipart form as it will reject almost anything a user might put there. Just use the base filename

Fix Multipart form processing: IllegalArgumentException: File path not allowed

---

aws-serverless-java-container-core/pom.xml
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/SecurityUtils.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsServletContext.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/AwsProxyRequest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequestTest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestFormTest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsServletContextTest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/model/AwsProxyRequestTest.java
aws-serverless-java-container-jersey/pom.xml
aws-serverless-java-container-jersey/src/main/java/com/amazonaws/serverless/proxy/jersey/JerseyLambdaContainerHandler.java
aws-serverless-java-container-jersey/src/test/java/com/amazonaws/serverless/proxy/jersey/EchoJerseyResource.java
aws-serverless-java-container-jersey/src/test/java/com/amazonaws/serverless/proxy/jersey/JerseyAwsProxyTest.java
aws-serverless-java-container-jersey/src/test/java/com/amazonaws/serverless/proxy/jersey/JerseyInjectionTest.java
aws-serverless-java-container-spring/pom.xml
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/SpringAwsProxyTest.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/SpringBootAppTest.java
aws-serverless-java-container-spring/src/test/resources/static/static.html
aws-serverless-java-container-struts2/pom.xml
aws-serverless-jersey-archetype/src/main/resources/archetype-resources/pom.xml
aws-serverless-spark-archetype/src/main/resources/archetype-resources/pom.xml
aws-serverless-struts2-archetype/src/main/resources/archetype-resources/pom.xml
samples/jersey/pet-store/pom.xml
samples/spark/pet-store/pom.xml
samples/struts/pet-store/pom.xml

*Issue #, if available:* Most of the issues in [milestone 16](https://github.com/awslabs/aws-serverless-java-container/milestone/16)
*Description of changes:* 
* Jackson updates to address the security alert
* Updated parse header function to simplify logic and avoid index out of bounds errors
* Fixed multipart form bugs
* Fixed issue with serving static content

Preparing for 1.3.2 release

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/ApacheCombinedServletLogFormatter.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/ApacheCombinedServletLogFormatterTest.java

*Issue #, if available:* N/A
- Previously logged as 01/01/1970:00:00:00Z as RequestTimeEpoch is == 0 (default) for ALB requests
- Added some tests to cover the fix

Bug Fix: Log request time from ALB requests

---

samples/micronaut/pet-store/docker-build.sh

It seems, for those who don't have bash as their default shell, [[ is not valid syntax for `sh` (it did not run on my machine running Linux Mint 19 and zsh as my default, I got multiple `./docker-build.sh: 4: ./docker-build.sh: [[: not found` errors). 
I would propose changing this to `#!/bin/bash`, for which this is definitely valid syntax.

Change default shell for execution

---

.github/workflows/continuous-integration-workflow.yml

GitHubActions checkout v1 --> v2

GitHub Actions checkout v2

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpApiV2ProxyHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletResponse.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/testutils/AwsProxyRequestBuilder.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/HttpApiV2ProxyRequest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletResponseTest.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/SpringAwsProxyTest.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/echoapp/EchoResource.java
aws-serverless-java-container-springboot2/src/test/java/com/amazonaws/serverless/proxy/spring/ServletAppTest.java
aws-serverless-java-container-springboot2/src/test/java/com/amazonaws/serverless/proxy/spring/servletapp/LambdaStreamHandler.java
aws-serverless-java-container-springboot2/src/test/java/com/amazonaws/serverless/proxy/spring/servletapp/MessageController.java
aws-serverless-java-container-struts2/src/test/java/com/amazonaws/serverless/proxy/struts2/Struts2AwsProxyTest.java

*Issue #, if available:* This PR addresses issues #358, #355, #352, #344, and #363.
*Description of changes:* Bug fixes to be included in patch release 1.5.1. See issues linked above

Merge fixes for patch release 1.5.1

---

.github/workflows/continuous-integration-workflow.yml
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/testutils/AwsProxyRequestBuilder.java
aws-serverless-java-container-spring/pom.xml
aws-serverless-spring-archetype/src/main/resources/archetype-resources/build.gradle
aws-serverless-spring-archetype/src/main/resources/archetype-resources/pom.xml
samples/spring/pet-store/build.gradle
samples/spring/pet-store/pom.xml

Currently the header map in HttpApiV2ProxyRequest cannot handle all lower-case headers. I replaced the standard HashMap with a TreeMap using the String.CASE_INSENSITIVE_ORDER comparator to ensure accommodate this.
This is a problem because headers arrive from the API Gateway in all lowercase, but in AwsHttpApiV2SecurityContext, for example, we checking for the capitalised Authorization header.

fix: ensuring that headers are case insensitive

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletResponseWriter.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/ServletLambdaContainerHandlerBuilder.java
aws-serverless-java-container-jersey/src/main/java/com/amazonaws/serverless/proxy/jersey/JerseyLambdaContainerHandler.java
aws-serverless-java-container-spark/src/main/java/com/amazonaws/serverless/proxy/spark/SparkLambdaContainerHandler.java
aws-serverless-java-container-springboot2/src/test/java/com/amazonaws/serverless/proxy/spring/ServletAppTest.java
aws-serverless-java-container-struts2/src/main/java/com/amazonaws/serverless/proxy/struts2/Struts2LambdaContainerHandler.java

*Issue #, if available:* #339 and #377 
*Description of changes:* Fixes an issue with the binary response content for ALB and bumps Spring 5.2 version to address [Spring's CVE](https://snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORK-1009832)

Release 1.5.2

---

aws-serverless-java-container-core/pom.xml
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/filters/UrlPathValidator.java
aws-serverless-java-container-jersey/pom.xml
aws-serverless-java-container-spark/pom.xml
aws-serverless-java-container-spring/pom.xml
aws-serverless-java-container-springboot2/pom.xml
aws-serverless-java-container-struts2/pom.xml

update jacoco and spotbugs, added activation dependency
please note the message "Coverage checks have not been met." for certain modules already happened for certain modules and is not related to the change

Allow compilation with JDK version >8 (update jacoco and spotbugs, added activation dependency)

---

aws-serverless-java-container-struts2/pom.xml
aws-serverless-java-container-struts2/src/main/java/com/amazonaws/serverless/proxy/struts2/Struts2LambdaHandler.java
aws-serverless-struts2-archetype/src/main/resources/archetype-resources/pom.xml

* Upgrade to latest available Struts GA version 2.5.26
* Use latest available dependency in Struts2 archetype

Upgrade to latest available Struts GA version 2.5.26

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpApiV2ProxyHttpServletRequest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpApiV2HttpServletRequestReaderTest.java

The V2 request object would not use the `cookies` field in the `2.0` schema. It would default to an empty array. See https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html for raw input details.
This change first checks of the `cookies` field is set on the underlying request POJO and will use that instead.

Fixing the cookies field in the v2 request object.

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpApiV2ProxyHttpServletRequest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpApiV2HttpServletRequestReaderTest.java

Reverts awslabs/aws-serverless-java-container#413 due to test failures

Revert "Fixing the cookies field in the v2 request object."

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/LambdaContainerHandler.java

This makes it a lot easier for frameworks that want
to use the module in GraalVM, to exclude Afterburner
(which does not work in GraalVM native image because
it generated classes at runtime)
- [ x ] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [ x ] I confirm that I've made a best effort attempt to update all relevant documentation.

Move afterburner registration to dedicated method

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestFormTest.java

#340 
* Empty form params are now available as part of the request object.
* Form param names are now included in getParameterNames()

Form param handling fixes

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpApiV2ProxyHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/testutils/AwsProxyRequestBuilder.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpApiV2HttpServletRequestReaderTest.java

*Issue #452*
For request v2 (HTTP APIs), read cookies from the dedicated section in addition to headers. HTTP APIs also filter cookies with no names.
Unsure if HTTP API will never send cookie in header; if so, we can remove the header parse section.
*Testing:*
`mvn test`

Add support for HTTP API cookie parameter

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/SecurityUtils.java

*Description of changes:* Added JavaDoc comment to explain the use of `@SupperWarnings` for path traversal in the security utils

docs: Documenting use of suppress warnings for path traversal

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/jaxrs/AwsProxySecurityContext.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletResponseWriter.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/testutils/AwsProxyRequestBuilder.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/AwsProxyRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/HttpApiV2ProxyRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/HttpApiV2ProxyRequestContext.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/RequestSource.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/model/HttpApiV2ProxyRequestTest.java

*Issue #489*
Adds ALB Context to Request Context. [Source](https://docs.aws.amazon.com/lambda/latest/dg/services-alb.html)
- [ X ] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [ X ] I confirm that I've made a best effort attempt to update all relevant documentation.

Add ALB Context to API GW Payload V2

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletResponseWriter.java

Fix provided for: https://github.com/awslabs/aws-serverless-java-container/issues/497
This is to resolve NullPointerException when HttpStatusCode is not present in default enum Response.StatusType
*Issue #, https://github.com/awslabs/aws-serverless-java-container/issues/497
- [/] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [ /] I confirm that I've made a best effort attempt to update all relevant documentation.

Fixing NullpointerException in case of non defined statusCode

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyRequestDispatcher.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsServletContext.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/FilterChainManager.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/testutils/MockServlet.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsFilterChainManagerTest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsServletContextTest.java

Implements ServletContext.getNamedDispatcher so it forwards to the correct servlet
Fixes #499

fix: Dispatch to the given servlet when using getNamedDispatcher

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletResponse.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletResponseTest.java

Setting the content type through a header should be equal to setting the content type using `setContentType`. In both cases the defined character set must be used for writing the result.

fix: Write resources using the charset defined in a Content-Type header

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpApiV2ProxyHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestTest.java

*Issue #, if available:* #511
Support `Accept-Language` header values which also contain a country part. 
Unlike mentioned in the GH issue, I did not use `Locale#forLanguageTag` to parse the language tag because it looks like invalid / unknown language tags result in an "empty" `Locale` object which I think might cause undesired side effects. 

gh-511 Support Accept-Language header values containing country subtag

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsServletContext.java

By using the class loader from the servlet context to load the servlet class, the servlet class will be able to find its resources from the class path.
Fixes #506

Load using the application class loader

---

aws-serverless-java-container-core/pom.xml
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsServletContext.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsServletContextTest.java

The correct mimetype for javascript is a requirement when loading javascript modules

fix: Provide correct mime type for javascript and css

---

aws-serverless-java-container-core/pom.xml
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestFormTest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/testutils/AwsProxyRequestBuilder.java
aws-serverless-java-container-jersey/src/test/java/com/amazonaws/serverless/proxy/jersey/JerseyParamEncodingTest.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/SpringAwsProxyTest.java
aws-serverless-java-container-struts/pom.xml

Removed the commons-fileupload while we wait for a new release based on Jakarta APIs.

Remove commons-fileupload

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsAsyncContext.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletResponse.java
aws-serverless-java-container-springboot3/src/test/java/com/amazonaws/serverless/proxy/spring/ServletAppTest.java
aws-serverless-java-container-springboot3/src/test/java/com/amazonaws/serverless/proxy/spring/servletapp/MessageController.java

Resolves #577
In `AwsAsyncContext` the listeners were notified too early effectively canceling the async context before the final dispatch.
This PR is rather trivial as it simply switches the order or operations.

GH-577 Ensure listeners are notified after dispatch

---

.gitignore
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/AwsProxyRequest.java
aws-serverless-java-container-springboot3/pom.xml
aws-serverless-java-container-springboot3/src/main/java/com/amazonaws/serverless/proxy/spring/SpringDelegatingLambdaContainerHandler.java
aws-serverless-java-container-springboot3/src/test/java/com/amazonaws/serverless/proxy/spring/SpringDelegatingLambdaContainerHandlerTests.java
aws-serverless-springboot3-archetype/src/main/resources/archetype-resources/build.gradle
samples/springboot3/alt-pet-store/README.md
samples/springboot3/alt-pet-store/builds.gradle
samples/springboot3/alt-pet-store/pom.xml
samples/springboot3/alt-pet-store/src/assembly/bin.xml
samples/springboot3/alt-pet-store/src/main/java/com/amazonaws/serverless/sample/springboot3/Application.java
samples/springboot3/alt-pet-store/src/main/java/com/amazonaws/serverless/sample/springboot3/controller/PetsController.java
samples/springboot3/alt-pet-store/src/main/java/com/amazonaws/serverless/sample/springboot3/filter/CognitoIdentityFilter.java
samples/springboot3/alt-pet-store/src/main/java/com/amazonaws/serverless/sample/springboot3/model/Error.java
samples/springboot3/alt-pet-store/src/main/java/com/amazonaws/serverless/sample/springboot3/model/Pet.java
samples/springboot3/alt-pet-store/src/main/java/com/amazonaws/serverless/sample/springboot3/model/PetData.java
samples/springboot3/alt-pet-store/src/main/resources/logback.xml
samples/springboot3/alt-pet-store/template.yml
samples/springboot3/pet-store/build.gradle

This new handler delegates to spring-cloud-function-serverless-web module which is managed by Spring team
This PR is a substitution for the one I canceled https://github.com/awslabs/aws-serverless-java-container/pull/578 and is better in a way that it requires user to opt-in to use this handler. The current AWS code is not touched providing a very smooth and safe transition.
I will also be publishing a sample on how to use it

Add implementation of delegating RequestStreamHandler

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/FilterChainManager.java

Fixed minor typographical errors in the Javadoc comments of FilterChainManager.
- [v] I confirm that my contribution is made under the terms of the Apache 2.0 license.
- [v] I confirm that I've made a best effort attempt to update all relevant documentation.

Fix typos in FilterChainManager comments

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequestTest.java

*Issue #, if available:* #573
Change the way that the parameters are transformed between API GW event and the Servlet request to avoid race condition when using parallel processing while using a HashMap object. Adding a ConcurrentHashMap will likely cause too big of a latency increase, so we move the parallel processing to earlier in the algorithm, and keep the rest simpler.
I added a few comments in the code to make it easier to understand.
We can have a broader discussion about this, and I didn't add any extra test cases. (but I wanted to submit this PR before going on vacation for 10 days)

Modify algorithm for parameter transformation logic

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpApiV2ProxyHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestFormTest.java

*Issue #, if available:* #633
Fixed Multipart files processing issue occurring when Array of files with same fieldName is sent in the request.

Fix: Multipart files processing when Array of files with same fieldName is sent in request

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/SecurityUtils.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpApiV2ProxyHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestTest.java

*Issue #, if available:*  #647
Fixed container returning incorrect serverName when using ALB as event source.

Fix: Incorrect ServerName with ALB

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/AwsProxyExceptionHandler.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/ServletLambdaContainerHandlerBuilder.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/AwsProxyExceptionHandlerTest.java
aws-serverless-java-container-spring/src/main/java/com/amazonaws/serverless/proxy/spring/SpringAwsProxyExceptionHandler.java
aws-serverless-java-container-spring/src/main/java/com/amazonaws/serverless/proxy/spring/SpringProxyHandlerBuilder.java
aws-serverless-java-container-spring/src/test/java/com/amazonaws/serverless/proxy/spring/SpringAwsProxyExceptionHandlerTest.java
aws-serverless-java-container-springboot3/src/main/java/com/amazonaws/serverless/proxy/spring/SpringBootAwsProxyExceptionHandler.java
aws-serverless-java-container-springboot3/src/main/java/com/amazonaws/serverless/proxy/spring/SpringBootProxyHandlerBuilder.java

handle Spring's ErrorResponse in separate default ExceptionHandlers

---

samples/springboot3/pet-store/pom.xml

Fixed missing maven references on Pet-Store sample project

pom.xml missing references fix

---

samples/springboot3/graphql-pet-store/README.md
samples/springboot3/graphql-pet-store/pom.xml
samples/springboot3/graphql-pet-store/src/assembly/bin.xml
samples/springboot3/graphql-pet-store/src/main/java/com/amazonaws/serverless/sample/springboot3/Application.java
samples/springboot3/graphql-pet-store/src/main/java/com/amazonaws/serverless/sample/springboot3/StreamLambdaHandler.java
samples/springboot3/graphql-pet-store/src/main/java/com/amazonaws/serverless/sample/springboot3/controller/PetsController.java
samples/springboot3/graphql-pet-store/src/main/java/com/amazonaws/serverless/sample/springboot3/filter/CognitoIdentityFilter.java
samples/springboot3/graphql-pet-store/src/main/java/com/amazonaws/serverless/sample/springboot3/model/Owner.java
samples/springboot3/graphql-pet-store/src/main/java/com/amazonaws/serverless/sample/springboot3/model/Pet.java
samples/springboot3/graphql-pet-store/src/main/resources/graphql/schema.graphqls
samples/springboot3/graphql-pet-store/src/main/resources/logback.xml
samples/springboot3/graphql-pet-store/template.yml

*Issue #715:*
Added SpringBoot3-GraphQl sample
Commands to test:
`sam build`
`sam local start-api`
`curl -X POST http://localhost:3000/graphql -d '{"query":"query petDetails {\n  petById(id: \"pet-1\") {\n      id\n      name\n      breed\n      owner {\n          id\n          firstName\n          lastName\n      }\n  }\n}","operationName":"petDetails"}' -H "Content-Type: application/json"
`
Test results:
`{"data":{"petById":{"id":"pet-1","name":"Alpha","breed":"Bulldog","owner":{"id":"owner-1","firstName":"Joshua","lastName":"Bloch"}}}}`

Added SpringBoot3-GraphQL sample

---

aws-serverless-java-container-springboot3/src/main/java/com/amazonaws/serverless/proxy/spring/AwsSpringHttpProcessingUtils.java
aws-serverless-java-container-springboot3/src/test/java/com/amazonaws/serverless/proxy/spring/SpringDelegatingLambdaContainerHandlerTests.java
aws-serverless-java-container-springboot3/src/test/java/com/amazonaws/serverless/proxy/spring/servletapp/ServletApplication.java
samples/springboot3/alt-pet-store/README.md
samples/springboot3/alt-pet-store/src/main/java/com/amazonaws/serverless/sample/springboot3/controller/PetsController.java

While concentrating on REST we somehow ignored standard request parameters. This fix addresses it for both v1 and v2 requests as well as adds tests and additional endpoint to a sample to verify
Resolves #754

GH-754 Fix request parameter parsing

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/HttpApiV2AuthorizerMap.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/model/HttpApiV2IamAuthorizer.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/model/HttpApiV2ProxyRequestTest.java

https://github.com/aws/serverless-java-container/issues/780
Add IAM authorizers in addition to existing JWT, Lambda authorizers
see also https://docs.aws.amazon.com/lambda/latest/dg/urls-invocation.html

Add support for IAM Authorizers in combination with 2.0 payload

---

aws-serverless-java-container-springboot3/pom.xml
aws-serverless-java-container-springboot3/src/main/java/com/amazonaws/serverless/proxy/spring/SpringDelegatingLambdaContainerHandler.java

#805 
Also updated to s-c-function-serverless-webb 4.1.1-SNAPSHOT This commit forces wait for full context initialization if context is created during snapstart creation

GH-805 Fix web context initialization during snapstart

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestTest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/testutils/AwsProxyRequestBuilder.java

*Issue #, if available:*  #816
ALB host header information comes in a singleValueHeader object, instead of the multivalueHeaders that was checked.
- Fixed the getRemoteHost and getRemotePort to return the correct values for ALB.
- Added a test to validate.

fix: getRemoteHost and getRemotePort for ALB

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequestTest.java

*Issue #, if available:* #909
Fixes bug introduced by #827
When using Lambda as target in ALB, Customers can configure either multi-value or single value headers. host header information then comes in either a singleValueHeader object or a multivalueHeaders object.
This PR adds support for both object types.
- Fixed the getRemoteHost and getRemotePort to return the correct values for ALB.
- Added a test to validate.

fix: Error with version 2.0.2 when multi-value header is active in alb

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsCookieProcessor.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpApiV2ProxyHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletResponse.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/CookieProcessor.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequestTest.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletResponseTest.java

*Issue #, if available:* #867 
*Description of changes:* 
Refactored the cookie processing logic to comply with RFC 6265 specifications.
* Introduced CookieProcessor interface and AwsCookieProcessor implementation:
* Encapsulates cookie parsing and formatting logic according to RFC 6265.
* Refactored AwsHttpServletResponse and AwsHttpServletRequest:
* Updated to use the CookieProcessor for all cookie-related operations.
* Centralized cookie handling logic by removing it from the AWS HTTP classes.
* Ensured proper handling of cookies with Max-Age=0:
* Cookies now expire immediately as specified by RFC 6265.

Update cookie handling to align with rfc6265 specifications

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/HttpUtils.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpApiV2ProxyHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequest.java
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsProxyHttpServletRequest.java
aws-serverless-java-container-springboot3/src/main/java/com/amazonaws/serverless/proxy/spring/AwsSpringHttpProcessingUtils.java
aws-serverless-java-container-springboot3/src/test/java/com/amazonaws/serverless/proxy/spring/SpringDelegatingLambdaContainerHandlerTests.java

*Issue #1084:*
if isBase64Encoded == true then AwsStringHttpProcessingUtils must decode the body

#1084: decode body if base64 is enable

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequest.java
aws-serverless-java-container-springboot3/src/main/java/com/amazonaws/serverless/proxy/spring/AwsSpringHttpProcessingUtils.java
aws-serverless-java-container-springboot3/src/test/java/com/amazonaws/serverless/proxy/spring/AwsSpringHttpProcessingUtilsTests.java

*Issue #, if available:* #1279
Added parameter decoding for ALB when using Spring Cloud.
When an ALB receives a request with URL-encoded query parameters, it passes those parameters to the Lambda function exactly as they were received, with the encoding intact. For example:
• Original URL: https://example.com/path?time=1970-01-01T00%3A00%3A00.004Z
• In the ALB event sent to Lambda: "time": "1970-01-01T00%3A00%3A00.004Z"
The %3A (representing :) remains encoded in the query parameter value.
This behavior differs from API Gateway, which automatically decodes URL-encoded query parameters before including them in the event object sent to Lambda functions. 
Currently when we use the classic way of mapping request events to servlet requests, things work fine as the decoding of …

fix: parameters encoding doesn't work for ALB when using Spring Cloud

---

aws-serverless-java-container-core/pom.xml
aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletRequest.java

This is to update dependency on commons-fileupload2-core from 2.0.0-M2 to 2.0.0-M4

Update Dependency: commons-fileupload2-jakarta-servlet6 to 2.0.0-M4

---

aws-serverless-java-container-core/src/main/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletResponse.java
aws-serverless-java-container-core/src/test/java/com/amazonaws/serverless/proxy/internal/servlet/AwsHttpServletResponseTest.java

Issue #1522
* remove response header if set with `null` value. 
* ignore `null` values when added to response header

fix: headers with null values removed from response
